<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ECommerce.Domain\ECommerce.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interfaces\" />
    <Folder Include="DTOs\" />
    <Folder Include="Features\OrderItems\Commands\UpdateOrderItem\" />
    <Folder Include="Features\OrderItems\Queries\GetAllOrderItems\" />
    <Folder Include="Features\OrderItems\Queries\GetOrderItemById\" />
    <Folder Include="Features\Payments\" />
    <Folder Include="Features\Orders\" />
    <Folder Include="Features\PromoCodes\" />
    <Folder Include="Features\Wishlists\Commands\UpdateWishlist\" />
    <Folder Include="Features\Wishlists\Queries\GetWishlistById\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
